name: flutter_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_auth: ^5.1.2
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  fluttertoast: ^8.2.8
  shared_preferences: ^2.3.3
  font_awesome_flutter: ^10.7.0
  toggle_switch: ^2.3.0
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  screenshot: ^3.0.0
  url_launcher: ^6.3.0
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
